import { img } from "./media";
import type { Project } from "./types";

/**
 * Proyectos REALES del estudio: renders finales de la NAS
 * (MIES_NAS/s/CLIENTES/<cliente>/<proyecto>/03 - Image/<fecha> To Send).
 * Las imágenes son COPIAS optimizadas para la web en public/media/projects/<slug>/
 * (máx. 2400 px, JPG calidad 82, sin metadatos); los originales de la NAS no se modifican.
 *
 * ⚠ Por confirmar con el cliente: permiso de cada constructora para publicar, ciudad
 *   de cada proyecto (hoy "Colombia") y los textos. El año sale de la carpeta
 *   "To Send" más reciente usada. La traducción al inglés está en projects-real-en.ts.
 */
const real = (slug: string, files: [number, number, string][]) =>
  files.map(([w, h, alt], i) => img(`/media/projects/${slug}/${String(i + 1).padStart(2, "0")}.jpg`, alt, w, h));

export const realProjects: Project[] = [
  {
    slug: "sinara",
    title: "Sinara",
    client: "Constructora Meléndez",
    location: "Colombia",
    year: 2026,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Conjunto residencial de torres entre la vegetación, con piscina, zonas sociales y apartamentos con vista a la montaña.",
    order: 1,
    cover: img("/media/projects/sinara/01.jpg", "Torres de Sinara entre la vegetación", 2400, 1680),
    images: real("sinara", [
      [2400, 1680, "Torres de Sinara entre la vegetación"],
      [2400, 1500, "Piscina de Sinara"],
      [2400, 1470, "Sala y comedor con vista"],
      [2400, 1470, "Habitación de apartamento"],
      [2400, 1333, "Cocina con isla"],
      [2400, 1470, "Habitación principal con vista a la montaña"],
      [2400, 1350, "Vista aérea del conjunto"],
      [2000, 1225, "Terraza social con zona BBQ"],
    ]),
  },
  {
    slug: "verdant",
    title: "Verdant",
    client: "Constructora Meléndez",
    location: "Colombia",
    year: 2024,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Torres residenciales con fachada verde, piscina, parque infantil y zonas sociales; interiores de apartamento amoblados.",
    order: 2,
    cover: img("/media/projects/verdant/01.jpg", "Torres de Verdant", 2000, 1350),
    images: real("verdant", [
      [2000, 1350, "Torres de Verdant"],
      [2400, 1955, "Vista aérea de Verdant en la ciudad"],
      [2000, 1000, "Parque infantil"],
      [2000, 1000, "Piscina"],
      [2000, 1000, "Salón social"],
      [2400, 1350, "Habitación de apartamento"],
      [2400, 1260, "Cocina"],
      [2400, 1350, "Sala y comedor con balcón"],
    ]),
  },
  {
    slug: "valle-alto",
    title: "Valle Alto",
    client: "Constructora Meléndez",
    location: "Colombia",
    year: 2026,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Conjunto de vivienda con piscina, parque infantil y portería; renders aéreos e interiores de apartamento.",
    order: 3,
    cover: img("/media/projects/valle-alto/01.jpg", "Piscina y torres de Valle Alto", 2000, 1125),
    images: real("valle-alto", [
      [2000, 1125, "Piscina y torres de Valle Alto"],
      [2400, 1349, "Vista aérea del conjunto"],
      [2000, 1125, "Portería y acceso"],
      [2000, 1125, "Parque infantil"],
      [2000, 1100, "Lobby"],
      [2400, 2400, "Balcón con vista al valle"],
      [2400, 1320, "Cocina abierta"],
      [2400, 1320, "Sala de apartamento"],
    ]),
  },
  {
    slug: "altavia",
    title: "Altavia",
    client: "Constructora Meléndez",
    location: "Colombia",
    year: 2025,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Torres sobre la avenida con piscina en terraza, spa y lobby; renders de fachada, zonas comunes e interiores.",
    order: 4,
    cover: img("/media/projects/altavia/01.jpg", "Torres de Altavia sobre la avenida", 2000, 1290),
    images: real("altavia", [
      [2000, 1290, "Torres de Altavia sobre la avenida"],
      [2000, 1290, "Vista aérea sobre la avenida"],
      [2000, 1750, "Fachada principal"],
      [2000, 1125, "Piscina en la terraza"],
      [2000, 1125, "Lobby"],
      [2000, 1180, "Spa"],
      [2400, 1411, "Habitación de apartamento"],
      [2400, 1440, "Sala de apartamento"],
    ]),
  },
  {
    slug: "nova-avenue",
    title: "Nova Avenue",
    client: "Constructora Colpatria – Meléndez",
    location: "Colombia",
    year: 2026,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Torres residenciales con piscina, lobby y parque infantil; renders al atardecer, zonas comunes e interiores.",
    order: 5,
    cover: img("/media/projects/nova-avenue/01.jpg", "Torres de Nova Avenue al atardecer", 2000, 1200),
    images: real("nova-avenue", [
      [2000, 1200, "Torres de Nova Avenue al atardecer"],
      [2400, 1560, "Vista aérea con la piscina"],
      [2000, 1200, "Fachada de las torres"],
      [2000, 1200, "Piscina"],
      [2000, 1200, "Lobby"],
      [2000, 1111, "Sala y comedor"],
      [2000, 1111, "Cocina"],
      [2000, 1200, "Parque infantil"],
    ]),
  },
  {
    slug: "insite",
    title: "Insite",
    client: "Constructora Meléndez",
    location: "Colombia",
    year: 2026,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Torre residencial en ciudad con piscina, gimnasio y lobby; renders aéreos del barrio e interiores.",
    order: 6,
    cover: img("/media/projects/insite/01.jpg", "Piscina con la torre de Insite", 2400, 1350),
    images: real("insite", [
      [2400, 1350, "Piscina con la torre de Insite"],
      [2400, 1350, "Vista aérea del barrio"],
      [2400, 1350, "Fachada desde la calle"],
      [2400, 1200, "Lobby"],
      [2400, 1200, "Gimnasio"],
      [2400, 2040, "Cocina"],
      [2400, 2040, "Sala de apartamento"],
      [2400, 1800, "Habitación de apartamento"],
    ]),
  },
  {
    slug: "mediterranium-hills",
    title: "Mediterranium Hills",
    client: "Constructora Índico",
    location: "Colombia",
    year: 2025,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Proyecto residencial con piscina en la azotea, jardín zen, coworking y zonas sociales rodeadas de vegetación.",
    order: 7,
    cover: img("/media/projects/mediterranium-hills/01.jpg", "Vista aérea de la azotea con piscina", 2400, 1350),
    images: real("mediterranium-hills", [
      [2400, 1350, "Vista aérea de la azotea con piscina"],
      [2400, 1350, "Jardín zen"],
      [2400, 1350, "Terraza social"],
      [2400, 1350, "Piscina en la azotea"],
      [2400, 1350, "Sala de juegos"],
      [2400, 1350, "Zona infantil"],
      [2400, 1350, "Salón comunal"],
      [1920, 2400, "Coworking"],
    ]),
  },
  {
    slug: "chipichape-gardens",
    title: "Chipichape Gardens",
    client: "Constructora Índico",
    location: "Colombia",
    year: 2024,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Torres residenciales con cancha múltiple, gimnasio y lobby; renders aéreos con los cerros e interiores.",
    order: 8,
    cover: img("/media/projects/chipichape-gardens/01.jpg", "Torre de Chipichape Gardens desde la calle", 2000, 1111),
    images: real("chipichape-gardens", [
      [2000, 1111, "Torre de Chipichape Gardens desde la calle"],
      [2000, 1111, "Torres del conjunto"],
      [2400, 1350, "Vista aérea con los cerros"],
      [2000, 1111, "Cancha múltiple"],
      [2000, 1111, "Gimnasio"],
      [2000, 1334, "Lobby"],
      [2400, 1380, "Sala de apartamento"],
      [2400, 1500, "Sala y comedor"],
    ]),
  },
  {
    slug: "hacienda-caanan",
    title: "Hacienda Caanán",
    client: "CFC",
    location: "Colombia",
    year: 2026,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Conjunto de apartamentos entre zonas verdes; renders de fachada, acceso e interiores con balcón y BBQ.",
    order: 9,
    cover: img("/media/projects/hacienda-caanan/01.jpg", "Torres de Hacienda Caanán", 2000, 1125),
    images: real("hacienda-caanan", [
      [2000, 1125, "Torres de Hacienda Caanán"],
      [2000, 1125, "Vista general con zonas verdes"],
      [2000, 1125, "Acceso vehicular"],
      [2400, 1320, "Sala y cocina"],
      [2400, 1320, "Sala y comedor con vista"],
      [2400, 1320, "Habitación principal"],
      [2400, 1320, "Balcón con BBQ"],
      [2400, 1080, "Comedor y balcón"],
    ]),
  },
  {
    slug: "trialto",
    title: "Trialto",
    client: "Jaramillo Mora",
    location: "Colombia",
    year: 2024,
    category: "residencial",
    services: ["3d-rendering"],
    summary: "Torres de uso mixto con terraza bar, piscina infinita con vista a la montaña, gimnasio al aire libre y lobby.",
    order: 10,
    cover: img("/media/projects/trialto/01.jpg", "Torres de Trialto al atardecer", 2000, 1125),
    images: real("trialto", [
      [2000, 1125, "Torres de Trialto al atardecer"],
      [2000, 1125, "Fachada con arborización"],
      [2400, 1350, "Vista aérea nocturna"],
      [2400, 1200, "Terraza bar"],
      [2000, 1000, "Gimnasio al aire libre"],
      [2000, 1370, "Lobby"],
      [2000, 1000, "Piscina infinita con vista a la montaña"],
      [2000, 1000, "Piscina en la azotea"],
    ]),
  },
];
