import type { Locale } from "@/lib/i18n";

/**
 * Textos de la interfaz en español e inglés.
 * ⚠ La versión en inglés es un BORRADOR (traducción inicial): la revisa el cliente.
 * Los textos de contenido (servicios, proyectos, estudio…) están en src/content/en.ts.
 */
const es = {
  lang: { label: "Idioma", switchTo: "Cambiar idioma" },
  common: {
    skip: "Saltar al contenido",
    homeAria: "MIES Group — inicio",
    menu: "Menú",
    close: "Cerrar",
    whatsappCta: "Escríbenos por WhatsApp",
    privacy: "Privacidad",
    inPage: "En esta página",
    breadcrumb: "Migas de pan",
    play: "Reproducir",
    pause: "Pausar",
    resume: "Reanudar",
    projectCount: (n: number) => `${n} ${n === 1 ? "proyecto" : "proyectos"}`,
  },
  nav: { home: "Inicio", projects: "Proyectos", vrGames: "VR/Juegos", studio: "Estudio", contact: "Contacto" },
  home: {
    title: "estudio 3D de visualización arquitectónica",
    sections: "Secciones",
    ctaProjects: "Ver proyectos",
    ctaVrGames: "Recorrer y jugar",
    studio: {
      description: (year: number, cities: string) => `Quiénes somos, videos del estudio y conferencias. Desde ${year}, en ${cities}.`,
      tag: (year: number) => `Desde ${year}`,
      cta: "Conocer el estudio",
    },
    contact: { description: "Cuéntanos de tu proyecto: WhatsApp, correo o formulario.", tag: "Respuesta en 24 h", cta: "Escribirnos" },
  },
  projects: {
    title: "Proyectos",
    description: "Portafolio de visualización arquitectónica: renders, animación CGI, tours 360°, realidad virtual, Web3D e IA.",
    intro: (n: number) => `${n} proyectos de visualización arquitectónica. Elige una categoría y abre cualquiera.`,
    categories: "Categorías",
    badgeNew: "Nuevo",
    badgeFeatured: "Destacado",
    viewProject: "ver proyecto",
    next: "Siguiente:",
    nextProject: "Siguiente proyecto",
    credit: "Un proyecto de MIES Group para",
    back: "← Proyectos",
    more: "Más proyectos",
  },
  vrGames: {
    description: "Realidad virtual a escala real y videojuegos jugables en el navegador, desarrollados por MIES Group.",
    vr: "Realidad virtual",
    games: "Juegos",
    gameplay: "Gameplay y trailers",
    play: "Jugar",
    playable: "Jugable",
    soon: "Próximamente",
    loading: "Cargando",
    restart: "Reiniciar",
    fullscreen: "Pantalla completa",
    exitFullscreen: "Salir",
    desktopOnly: "Este juego está pensado para computador. Mira el gameplay mientras tanto:",
  },
  studio: {
    title: "Estudio",
    description: "MIES Group: estudio 3D fundado en 2015. Quiénes somos, videos del estudio (Channel) y conferencias.",
    about: "Quiénes somos",
    founded: "Fundado",
    offices: "Sedes",
    contact: "Contacto",
    channel: "Channel",
    channelIntro: "Reels, animaciones y making-of del estudio.",
    subscribe: "Suscribirse en YouTube →",
    conferences: "Conferencias",
    conferencesIntro: "Compartimos lo que aprendemos en eventos de construcción, arquitectura y tecnología.",
    join: "Trabaja con nosotros",
    joinText: "Buscamos artistas 3D, desarrolladores en tiempo real y perfiles de arquitectura.",
    joinCta: "Envíanos tu portafolio",
    joinSubject: "Portafolio — Trabaja con nosotros",
  },
  contact: {
    title: "Contacto",
    description: "Cuéntanos de tu proyecto de visualización 3D, animación, tour 360°, VR o Web3D.",
    phones: "Teléfonos",
    offices: "Sedes",
    formTitle: "O escríbenos aquí",
  },
  form: {
    name: "Nombre",
    email: "Correo",
    phone: "Teléfono / WhatsApp",
    projectType: "Tipo de proyecto",
    choose: "Selecciona…",
    other: "Otro",
    message: "Cuéntanos del proyecto (opcional)",
    notice:
      "Usamos estos datos solo para responder tu solicitud y darle seguimiento. No los vendemos ni los usamos con inteligencia artificial, y puedes pedir que los borremos cuando quieras.",
    consentBefore: "Autorizo el tratamiento de mis datos según la",
    consentLink: "política de privacidad",
    send: "Enviar",
    mock: "Mockup: el envío es simulado.",
    sentTitle: "Mensaje recibido",
    sentText: "Te respondemos en menos de 24 horas hábiles.",
    errors: {
      name: "Escribe tu nombre",
      email: "Correo no válido",
      phone: "Escribe un teléfono",
      phoneInvalid: "Teléfono no válido",
      projectType: "Elige un tipo de proyecto",
      privacy: "Debes aceptar la política de datos",
    },
  },
};

type Dict = typeof es;

const en: Dict = {
  lang: { label: "Language", switchTo: "Change language" },
  common: {
    skip: "Skip to content",
    homeAria: "MIES Group — home",
    menu: "Menu",
    close: "Close",
    whatsappCta: "Message us on WhatsApp",
    privacy: "Privacy",
    inPage: "On this page",
    breadcrumb: "Breadcrumb",
    play: "Play",
    pause: "Pause",
    resume: "Resume",
    projectCount: (n) => `${n} ${n === 1 ? "project" : "projects"}`,
  },
  nav: { home: "Home", projects: "Projects", vrGames: "VR/Games", studio: "Studio", contact: "Contact" },
  home: {
    title: "architectural visualization 3D studio",
    sections: "Sections",
    ctaProjects: "View projects",
    ctaVrGames: "Explore and play",
    studio: {
      description: (year, cities) => `Who we are, studio videos and talks. Since ${year}, in ${cities}.`,
      tag: (year) => `Since ${year}`,
      cta: "Meet the studio",
    },
    contact: { description: "Tell us about your project: WhatsApp, email or form.", tag: "Reply within 24 h", cta: "Get in touch" },
  },
  projects: {
    title: "Projects",
    description: "Architectural visualization portfolio: renders, CGI animation, 360° tours, virtual reality, Web3D and AI.",
    intro: (n) => `${n} architectural visualization projects. Pick a category and open any of them.`,
    categories: "Categories",
    badgeNew: "New",
    badgeFeatured: "Featured",
    viewProject: "view project",
    next: "Next:",
    nextProject: "Next project",
    credit: "A MIES Group project for",
    back: "← Projects",
    more: "More projects",
  },
  vrGames: {
    description: "Real-scale virtual reality and browser-playable video games by MIES Group.",
    vr: "Virtual reality",
    games: "Games",
    gameplay: "Gameplay and trailers",
    play: "Play",
    playable: "Playable",
    soon: "Coming soon",
    loading: "Loading",
    restart: "Restart",
    fullscreen: "Fullscreen",
    exitFullscreen: "Exit",
    desktopOnly: "This game is designed for desktop. Watch the gameplay in the meantime:",
  },
  studio: {
    title: "Studio",
    description: "MIES Group: 3D studio founded in 2015. Who we are, studio videos (Channel) and talks.",
    about: "Who we are",
    founded: "Founded",
    offices: "Offices",
    contact: "Contact",
    channel: "Channel",
    channelIntro: "Reels, animations and making-of from the studio.",
    subscribe: "Subscribe on YouTube →",
    conferences: "Talks",
    conferencesIntro: "We share what we learn at construction, architecture and technology events.",
    join: "Work with us",
    joinText: "We're looking for 3D artists, real-time developers and architecture profiles.",
    joinCta: "Send us your portfolio",
    joinSubject: "Portfolio — Work with us",
  },
  contact: {
    title: "Contact",
    description: "Tell us about your 3D visualization, animation, 360° tour, VR or Web3D project.",
    phones: "Phones",
    offices: "Offices",
    formTitle: "Or write to us here",
  },
  form: {
    name: "Name",
    email: "Email",
    phone: "Phone / WhatsApp",
    projectType: "Project type",
    choose: "Choose…",
    other: "Other",
    message: "Tell us about the project (optional)",
    notice:
      "We use this information only to answer your request and follow up on it. We don't sell it or use it with artificial intelligence, and you can ask us to delete it at any time.",
    consentBefore: "I authorize the processing of my data according to the",
    consentLink: "privacy policy",
    send: "Send",
    mock: "Mockup: sending is simulated.",
    sentTitle: "Message received",
    sentText: "We'll get back to you within 24 business hours.",
    errors: {
      name: "Please enter your name",
      email: "Invalid email",
      phone: "Please enter a phone number",
      phoneInvalid: "Invalid phone number",
      projectType: "Please choose a project type",
      privacy: "You must accept the data policy",
    },
  },
};

export const ui: Record<Locale, Dict> = { es, en };
export const t = (lang: Locale) => ui[lang];
